# .github/workflows/scheduled.yml
name: Run at 12:10 PM

on:
  schedule:
    - cron: '10 8 * * *'  # Runs at 2:10 PM IST (which is 8:10 AM UTC)

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello! It's 12:10 PM IST 🎉"
